name: basic_diagram_example
description: A basic example of using the custom_paint_diagram_layer package.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  custom_paint_diagram_layer:
    git:
      url: https://github.com/zartyblartfast/custom_paint_diagram_layer.git
      ref: v0.0.1  # Use the latest tagged version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
